name: Tests

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

permissions:
  contents: read

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-v${{ matrix.node }}-npm-
            ${{ matrix.os }}-node-v${{ matrix.node }}-
            ${{ matrix.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run test:lint

  audit:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-v${{ matrix.node }}-npm-
            ${{ matrix.os }}-node-v${{ matrix.node }}-
            ${{ matrix.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Audit
        run: npm run audit

  test-unit:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-v${{ matrix.node }}-npm-
            ${{ matrix.os }}-node-v${{ matrix.node }}-
            ${{ matrix.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Test unit
        run: npm run test:unit -- --coverage --maxWorkers=2

      - name: Test unit (Vue 3)
        run: npm run test:unit -- --coverage --maxWorkers=2
        env:
          USE_VUE3: '1'

      - name: Merge coverage
        run:
          npx istanbul-merge --out ./coverage-final.json coverage/coverage-final.json
          coverage-vue3/coverage-final.json

      - name: CodeCov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          files: ./coverage-final.json
